import { jsonToCSV, downloadCSV } from './csvParser';

/**
 * Field definitions for items import/export
 * Columns match the standard Excel inventory file
 */
export const ITEM_IMPORT_FIELDS = {
  // Required
  'Item Name': { required: true, type: 'string', description: 'Item name' },

  // Product details
  'Selling Price': { required: false, type: 'number', description: 'Selling price' },
  'Brand': { required: false, type: 'string', description: 'Brand name' },
  'Manufacturer': { required: false, type: 'string', description: 'Manufacturer name' },
  'Size': { required: false, type: 'string', description: 'Product size' },
  'Colour': { required: false, type: 'string', description: 'Product colour' },
  'HSN/SAC': { required: false, type: 'string', description: 'HSN/SAC code (4-8 digits)' },
  'Purchase Price': { required: false, type: 'number', description: 'Cost / purchase price' },
  'Category Name': { required: false, type: 'string', description: 'Category name (auto-matched or created)' },
  'Tax Rate': { required: false, type: 'number', description: 'GST tax rate (%)' },
  'Reorder Point': { required: false, type: 'number', description: 'Reorder level', default: 0 },
};

/**
 * Column order for import template
 */
export const IMPORT_COLUMN_ORDER = [
  'Item Name',
  'Selling Price',
  'Brand',
  'Manufacturer',
  'Size',
  'Colour',
  'HSN/SAC',
  'Purchase Price',
  'Category Name',
  'Tax Rate',
  'Reorder Point',
];

/**
 * Column order for export (uses DB column names)
 */
export const EXPORT_COLUMN_ORDER = [
  'item_name',
  'sku',
  'unit_price',
  'cost_price',
  'brand',
  'manufacturer',
  'size',
  'color',
  'hsn_code',
  'tax_rate',
  'category_name',
  'reorder_point',
  'current_stock',
  'unit_of_measurement',
  'is_active',
];

/**
 * Generate CSV template with sample data matching our Excel format
 */
export const generateImportTemplate = () => {
  const sampleData = [
    {
      'Item Name': 'DOPE',
      'Selling Price': '34283.82',
      'Brand': 'EMOTORAD',
      'Manufacturer': 'INKODOP TECHNOLOGIES PVT LTD',
      'Size': '',
      'Colour': 'BLACK',
      'HSN/SAC': '87116090',
      'Purchase Price': '17141.91',
      'Category Name': '24-S/S',
      'Tax Rate': '5',
      'Reorder Point': '1',
    },
    {
      'Item Name': 'HEIST X2',
      'Selling Price': '25000',
      'Brand': 'PYLOGON',
      'Manufacturer': 'BLITZ',
      'Size': 'XL-M/S',
      'Colour': 'GREEN',
      'HSN/SAC': '87120010',
      'Purchase Price': '15000',
      'Category Name': '24-S/S',
      'Tax Rate': '5',
      'Reorder Point': '1',
    },
  ];

  const csv = jsonToCSV(sampleData, IMPORT_COLUMN_ORDER);
  downloadCSV(csv, `items_import_template_${new Date().toISOString().split('T')[0]}.csv`);
};

/**
 * Map CSV row to backend item creation format.
 * Supports both our Excel column names and legacy column names.
 */
export const mapCSVToItemData = (csvRow: any): any => {
  // Support both Excel-style headers and legacy headers
  const name = csvRow['Item Name'] || csvRow['item_name'] || csvRow['name'];
  const sellingPrice = csvRow['Selling Price'] || csvRow['unit_price'] || csvRow['selling_price'];
  const brand = csvRow['Brand'] || csvRow['brand'];
  const manufacturer = csvRow['Manufacturer'] || csvRow['manufacturer'];
  const size = csvRow['Size'] || csvRow['size'];
  const colour = csvRow['Colour'] || csvRow['COLOUR'] || csvRow['color'];
  const hsnCode = csvRow['HSN/SAC'] || csvRow['hsn_code'] || csvRow['HSN Code'];
  const costPrice = csvRow['Purchase Price'] || csvRow['cost_price'];
  const categoryName = csvRow['Category Name'] || csvRow['category_name'] || csvRow['category'];
  const taxRate = csvRow['Tax Rate'] || csvRow['Intra State Tax Rate'] || csvRow['tax_rate'];
  const reorderPoint = csvRow['Reorder Point'] || csvRow['reorder_point'];

  return {
    name: name?.toString().trim() || '',
    // SKU is auto-generated by backend — no need to provide
    unit: csvRow['unit_of_measurement'] || 'pieces',
    unit_price: sellingPrice ? parseFloat(sellingPrice) : 0,
    cost_price: costPrice ? parseFloat(costPrice) : 0,
    brand: brand?.toString().trim() || null,
    manufacturer: manufacturer?.toString().trim() || null,
    size: size?.toString().trim() || null,
    color: colour?.toString().trim() || null,
    hsn_code: hsnCode?.toString().trim() || null,
    category_name: categoryName?.toString().trim() || null,
    tax_rate: taxRate ? parseFloat(taxRate) : 0,
    reorder_point: reorderPoint ? parseInt(reorderPoint) : 0,
    is_active: true,
  };
};

/**
 * Map Item to CSV export format
 */
export const mapItemToCSV = (item: any): any => {
  return {
    item_name: item.item_name,
    sku: item.sku,
    unit_price: item.unit_price,
    cost_price: item.cost_price,
    brand: item.brand || '',
    manufacturer: item.manufacturer || '',
    size: item.size || '',
    color: item.color || '',
    hsn_code: item.hsn_code || '',
    tax_rate: item.tax_rate,
    category_name: item.category_name || '',
    reorder_point: item.reorder_point,
    current_stock: item.current_stock,
    unit_of_measurement: item.unit_of_measurement,
    is_active: item.is_active,
  };
};
